### ISSUE TITLE
I'm Getting This Error Every Time I Run iRecovery

### ISSUE THREAD

**Issue by XboxOneSogie720** [libimobiledevice/libirecovery#107]
I just finished building libirecovery on Linux Mint. Everything went fine, and it installed correctly. I can even press tab while typing the command in terminal, meaning that in theory, irecovery should now work. However, this is not the case. When running any command, it gives me this error, shown in the attachment.
![error](https://user-images.githubusercontent.com/109363013/209398723-35ca0fd7-6a75-45fb-98fd-86dd0fda5ace.png)

**Comment by nikias** [comment]
Have you tried to run `sudo ldconfig` ?

**Comment by XboxOneSogie720** [comment]
@nikias I didn't even know that command existed. It'd be nice if it was in the readme, and if it wasn't, then I just missed it. Anyways, that worked. Thanks!
