### ISSUE TITLE
Won't compile?

### ISSUE THREAD

**Issue by dayt0n** [libimobiledevice/libirecovery#11]
So I am attempting to compile this and as I run <pre>sh autogen.sh</pre> it gives me this and refuses to "autogen": <pre>glibtoolize: putting auxiliary files in `.'.
glibtoolize: linking file `./ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIR, `m4'.
glibtoolize: linking file `m4/libtool.m4'
glibtoolize: linking file `m4/ltoptions.m4'
glibtoolize: linking file `m4/ltsugar.m4'
glibtoolize: linking file `m4/ltversion.m4'
glibtoolize: linking file `m4/lt~obsolete.m4'
configure.ac:6: error: Autoconf version 2.65 or higher is required
/usr/local/Cellar/automake/1.14.1/share/aclocal-1.14/init.m4:29: AM_INIT_AUTOMAKE is expanded from...
configure.ac:6: the top level
autom4te: /sw/bin/m4 failed with exit status: 63
aclocal: error: echo failed with exit status: 63
configure.ac: error: no proper invocation of AM_INIT_AUTOMAKE was found.
configure.ac: You should verify that configure.ac invokes AM_INIT_AUTOMAKE,
configure.ac: that aclocal.m4 is present in the top-level directory,
configure.ac: and that aclocal.m4 was recently regenerated (using aclocal)
src/Makefile.am:11: error: WIN32 does not appear in AM_CONDITIONAL
src/Makefile.am:6: error: Libtool library used but 'LIBTOOL' is undefined
src/Makefile.am:6:   The usual way to define 'LIBTOOL' is to add 'LT_INIT'
src/Makefile.am:6:   to 'configure.ac' and run 'aclocal' and 'autoconf' again.
src/Makefile.am:6:   If 'LT_INIT' is in 'configure.ac', make sure
src/Makefile.am:6:   its definition is in aclocal's search path.
/usr/local/Cellar/automake/1.14.1/share/automake-1.14/am/depend2.am: error: am__fastdepCC does not appear in AM_CONDITIONAL
/usr/local/Cellar/automake/1.14.1/share/automake-1.14/am/depend2.am:   The usual way to define 'am__fastdepCC' is to add 'AC_PROG_CC'
/usr/local/Cellar/automake/1.14.1/share/automake-1.14/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
/usr/local/Cellar/automake/1.14.1/share/automake-1.14/am/depend2.am: error: AMDEP does not appear in AM_CONDITIONAL
/usr/local/Cellar/automake/1.14.1/share/automake-1.14/am/depend2.am:   The usual way to define 'AMDEP' is to add one of the compiler tests
/usr/local/Cellar/automake/1.14.1/share/automake-1.14/am/depend2.am:     AC_PROG_CC, AC_PROG_CXX, AC_PROG_OBJC, AC_PROG_OBJCXX,
/usr/local/Cellar/automake/1.14.1/share/automake-1.14/am/depend2.am:     AM_PROG_AS, AM_PROG_GCJ, AM_PROG_UPC
/usr/local/Cellar/automake/1.14.1/share/automake-1.14/am/depend2.am:   to 'configure.ac' and run 'aclocal' and 'autoconf' again
./configure: line 1789: syntax error near unexpected token `dist-bzip2'
./configure: line 1789: `AM_INIT_AUTOMAKE(dist-bzip2 no-dist-gzip)'</pre>
Now, I will tell you that I have autoconf version 2.69. So I have no idea why it is telling me I do not have version 2.65 or above. Please help. Thanks!

**Comment by FunkyM** [comment]
You should have checked the output of `$ autoconf --version` but then you appear to have fixed it yourself?
