### ISSUE TITLE
device not detected on windows

### ISSUE THREAD

**Issue by mexmer** [libimobiledevice/libirecovery#112]
seems apple driver changed device insterface path

old ioctl based driver generated path like this
\\?\usb#vid_05ac&pid_1281#sdom:01_cpid:8010_cprv:11_cpfm:03_scep:01_bdid:0c_ecid:ECIDNUMBER_ibfl:3d_srnm:[DEVICESERIAL]#{b8085869-feb9-404b-8cb1-1e5c14fa8c54}\0000

newer winusb based driver generates path like this
\\?\usb#vid_05ac&pid_1281&mi_01#7&fe42a63&0&0001#{b8085869-feb9-404b-8cb1-1e5c14fa8c54}\usb#vid_05ac&pid_1281#sdom:01_cpid:8010_cprv:11_cpfm:03_scep:01_bdid:0c_ecid:ECIDNUMBER_ibfl:3d_srnm:[DEVICESERIAL]#mux1

because libidevicerecovery cannot parse serial from deviceinstancepath, it bails out.

if i replace winusb driver with ioctl driver, it works properly

**Comment by nikias** [comment]
Should be resolved.
