### ISSUE TITLE
Need updated version so idevicerestore will build

### ISSUE THREAD

**Issue by elekven-m** [libimobiledevice/libirecovery#116]
Not generating libirecovery-1.0.1 as required by idevicerestore, at least for mingw64 build. Still creating libirecovery-1.0.dll.

**Comment by nikias** [comment]
Yes I know. Release imminent.

**Comment by JayPop64** [comment]
Is there an ETA for the release?

**Comment by nikias** [comment]
https://github.com/libimobiledevice/libirecovery/releases/tag/1.1.0
