### ISSUE TITLE
Unable to discover device type

### ISSUE THREAD

**Issue by anityak** [libimobiledevice/libirecovery#128]
<img width="959" alt="image" src="https://github.com/libimobiledevice/libirecovery/assets/57673134/4f827c2d-9734-4a9d-8b5e-021f1e183f92">

pls help my iphone 12 is stuck on recovery i need to restore it

**Comment by nikias** [comment]
Outdated idevicerestore and libirecovery as per discussion in the Telegram group. Closing,
