### ISSUE TITLE
configure: error: Package requirements (libusb-1.0 >= 1.0.3) were not met:  No package 'libusb-1.0' found

### ISSUE THREAD

**Issue by mcjoeng** [libimobiledevice/libirecovery#15]
![snapshot12](https://cloud.githubusercontent.com/assets/10485304/6551964/41b229ec-c67b-11e4-9f9c-002d666726bd.png)

Help ! 
I have installed libusb-1.0 from http://download.opensuse.org/repositories/home:/FunkyM:/iOS/openSUSE_13.2/ . 
But it noticed me that "configure: error: Package requirements (libusb-1.0 >= 1.0.3) were not met:  No package 'libusb-1.0' found"

**Comment by mcjoeng** [comment]
Is it the problem of libusb-0_1-4?

![snapshot13](https://cloud.githubusercontent.com/assets/10485304/6552181/17dfe23c-c67e-11e4-91c1-97a22d55e6fa.png)

**Comment by mcjoeng** [comment]
![snapshot14](https://cloud.githubusercontent.com/assets/10485304/6552223/8ca646ce-c67e-11e4-8a52-7c241405eb28.png)

I find two libusb installed

**Comment by nikias** [comment]
You need to install ```libusb-1_0-devel```. This is a default procedure and not an issue with libirecovery.
