### ISSUE TITLE
How can i execute restore program with command line successfully?

### ISSUE THREAD

**Issue by Fengzk** [libimobiledevice/libirecovery#17]
After compile the idevicerestore program, which cmd line should i  use to execute the program?
I have ipsw file in my disk and do not need to download it from internet. I don't know the meaning of the command line parameters. Thanks for any comments.

**Comment by FunkyM** [comment]
Please see the README and run the program without arguments to see a usage description.
Also please mind that this is the issue tracker for "libirecovery". There is another one for "idevicerestore" which would be better suited for questions.
