### ISSUE TITLE
Release for homebrew integration

### ISSUE THREAD

**Issue by ebekebe** [libimobiledevice/libirecovery#22]
libirecovery is a requirement of idevicerestore, which expects at least version 0.0.2. I currently try to make a homebrew formula that builds idevicerestore and for that I created a formula for libirecovery. Since homebrew accepts only tagged versions it would be cool if you could make a new 0.0.2 release, so I can progress with the formula.

Related pull request: https://github.com/Homebrew/homebrew-core/pull/1259

**Comment by awesomebing1** [comment]
I would like to see this as well, please.

**Comment by bjoernhaeuser** [comment]
That would be really amazing :)

**Comment by spotlightishere** [comment]
Is there any update about having a release for this?

**Comment by FunkyM** [comment]
Closing as version [1.0.0](/libimobiledevice/libirecovery/releases/tag/1.0.0) has been released.
