### ISSUE TITLE
please release 0.2.0

### ISSUE THREAD

**Issue by glensc** [libimobiledevice/libirecovery#25]
please release libirecovery 0.2.0 because [idevicerestore/configure.ac:18](https://github.com/libimobiledevice/idevicerestore/blob/950fbae391f34d6c31e087359515c755b49b7eff/configure.ac#L18) requires it, so dependencies of idevicerestore could be included in linux distro

**Comment by FunkyM** [comment]
Closing as version [1.0.0](/libimobiledevice/libirecovery/releases/tag/1.0.0) has been released.
