### ISSUE TITLE
should retry be incremented in the loop ?

### ISSUE THREAD

**Issue by dp111** [libimobiledevice/libirecovery#31]
line 1789 of libirecovery.c
`
		if (!recovery_mode && status != 5) {
			int retry = 0;

			while (retry < 20) {
				irecv_get_status(client, &status);
				if (status == 5) {
					break;
				}
				sleep(1);
			}

			if (status != 5) {
				return IRECV_E_USB_UPLOAD;
			}
		}`

**Comment by nikias** [comment]
Fixed with commit fdaddb539e8d2f25ccc8cc66d8c1e36cfee83e02. Good catch!
