### ISSUE TITLE
iPad6,11 (J71tAP) missing in irecv_devices[]

### ISSUE THREAD

**Issue by iakdev** [libimobiledevice/libirecovery#38]
{"iPad6,11", "j71tap", 0x10, 0x8003},

needs to get added to irecv_devices[] in libirecovery/src/libirecovery.c to support the device.

See: https://github.com/libimobiledevice/idevicerestore/issues/215

**Comment by nikias** [comment]
Done with commit 260cb0684bf1cb7d2cdef8ce4a1ec6d832eb1d1c. Thank!
