### ISSUE TITLE
add support for the Spring 2020 iPad Pros and iPhone SE

### ISSUE THREAD

**Issue by DanTheMann15** [libimobiledevice/libirecovery#61]
// iPad Pro 11-inch (2020) WiFi //
Model: iPad8,9
Board: j417ap
Platform: t8027
APBoardID: 0x3C

// iPad Pro 11-inch (2020) WiFi + Cellular //

Model: iPad8,10
Board: j418ap
Platform: t8027
APBoardID: 0x3E
BBChipID: 0x00000068

// iPad Pro 12.9-inch (2020) WiFi //
Model: iPad8,11
Board: j420ap
Platform: t8027
APBoardID: 0x38

// iPad Pro 12.9-inch (2020) WiFi + Cellular //

Model: iPad8,12
Board: j421ap
Platform: t8027
APBoardID: 0x3A
BBChipID: 0x00000068

--------------------

IPSW Links:
11-inch: https://updates.cdn-apple.com/2020WinterFCS/fullrestores/041-42554/2971A61F-8071-43AC-93BB-F68D1BEAD94E/iPad_Spring_2020_13.4_17E255_Restore.ipsw

12.9-inch: https://updates.cdn-apple.com/2020WinterFCS/fullrestores/041-44040/C7006F64-A1F3-4671-84A3-2E77DFB04A8E/iPad8,11,iPad8,12_13.4_17E255_Restore.ipsw

**Comment by nikias** [comment]
Hmm isn't there also a 12.9 inch model?

**Comment by DanTheMann15** [comment]
yes there is, but there is currently no info for those yet.

thats why i posted this for iPad8,9 and 8,10 since apple goofed-up and posted the wrong ipsw early.

**Comment by nikias** [comment]
oh right... it was the fuckup haha

**Comment by DanTheMann15** [comment]
Good mother of god apple, another device...
well, here are the specifications to help add support:

// iPhone SE (2020) //

Model: iPhone12,8
Board: d79ap
Platform: t8030
APBoardID: 0x10
BBChipID: 0x00000068
