### ISSUE TITLE
Macos 10.15.4 PKG_CHECK_MODULES error during ./autogen.sh (and potensial fix)

### ISSUE THREAD

**Issue by stemnic** [libimobiledevice/libirecovery#62]
Hi,

I tried compiling libirecovery today and ran into a error with `PKG_CHECK_MODULES`

```
checking for PTHREAD_PRIO_INHERIT... yes
./configure: line 17646: syntax error near unexpected token `libusb,'
./configure: line 17646: `			PKG_CHECK_MODULES(libusb, libusb-1.0 >= $LIBUSB_VERSION)'
```

Is this not the wrong syntax for PKG_CHECK_MODULES? [CMake](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html)

My fix was to remove the comma from `PKG_CHECK_MODULES` in configure
`PKG_CHECK_MODULES(libusb libusb-1.0 >= $LIBUSB_VERSION)`

**Comment by nikias** [comment]
It is autoconf, not cmake. And the syntax is definitely correct. Do you have `pkg-config` installed in the first place?

**Comment by stemnic** [comment]
Yes pkg-config is installed though brew and all of the requirements mentioned in the README
```
stemnic@mac ~ % pkg-config --version
0.29.2
```
It compiled and installed just fine.

Though I see now that I don't get the error anymore when i started from scratch again with a new copy of the git repo. So i'm guessing I just encountered some weird behaviour, since I missed a couple of the dependencies when I tried to build the first time.

**Comment by leehfather** [comment]
Same errors help me 

![image](https://user-images.githubusercontent.com/73723393/110056691-f4f91480-7d67-11eb-94b0-9cdfd3ce97aa.jpeg)

**Comment by leehfather** [comment]
> Hi help me i have the same issue did you fix it ? 
> 
> 
> 
> I tried compiling libirecovery today and ran into a error with `PKG_CHECK_MODULES`
> 
> 
> 
> ```
> 
> checking for PTHREAD_PRIO_INHERIT... yes
> 
> ./configure: line 17646: syntax error near unexpected token `libusb,'
> 
> ./configure: line 17646: `			PKG_CHECK_MODULES(libusb, libusb-1.0 >= $LIBUSB_VERSION)'
> 
> ```
> 
> 
> 
> Is this not the wrong syntax for PKG_CHECK_MODULES? [CMake](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html)
> 
> 
> 
> My fix was to remove the comma from `PKG_CHECK_MODULES` in configure
> 
> `PKG_CHECK_MODULES(libusb libusb-1.0 >= $LIBUSB_VERSION)`
> 
> 
> 
>

**Comment by nikias** [comment]
@leehfather that's not correct. You are missing pkgconfig on your system. If this is macOS, try this:
```
mkdir -p limd-build
cd limd-build
curl -o ./limd-build-macos.sh -Ls https://git.io/JLNVm
chmod +x ./limd-build-macos.sh
./limd-build-macos.sh
```
