### ISSUE TITLE
Restoring iPhone 5c (dfu mode)

### ISSUE THREAD

**Issue by soswag** [libimobiledevice/libirecovery#8]
If you start in DFU mode, after the iBEC is uploaded an attempt is made to put the device into restore mode, which fails because line 439 says "break;" if the device isn't switched to dfu mode in 500 milliseconds. This stems from a problem in /libirecovery-master/src/irecovery.c

Go to line number 429 change 

break;

to

return 0;

and recompile....this fixes all the issues like if you start out in dfu mode and it needs to go to restore mode after uploading the iBEC and it will just tell you it can't go into restore mode. This fix works on all devices. Your code was breaking from the For, Loop after one attempt. Now it will return 0 when it succeeds and continue the loop when it doesn't.

**Comment by FunkyM** [comment]
Are you talking about idevicerestore or about manually uploading iBEC from DFU using irecovery?

**Comment by daniel-bluesea** [comment]
hi soswag,

can you please elaborate a little regarding your fix? 

maybe the code has changed and line 429 is not where it used to be :)

thanks

**Comment by nikias** [comment]
@daniel-bluesea whatever this 'fix' was about, the current libirecovery + idevicerestore do work, on supported platforms (linux/mac).

Closing this ticket because no feedback was given and the alleged issue (and fix) was never proven to exist.
